# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('myshop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMessage',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, db_column='cart_id', primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('xiaoji', models.FloatField()),
                ('price', models.FloatField()),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='myshop.ManagerMessage')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsAddress',
            fields=[
                ('address_id', models.AutoField(auto_created=True, db_column='address_id', primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, db_column='order_id', primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_num', models.CharField(max_length=50)),
                ('order_status', models.IntegerField(default=0)),
                ('total', models.FloatField()),
                ('address', models.ForeignKey(db_column='address_id', default='', on_delete=django.db.models.deletion.CASCADE, to='cart.GoodsAddress')),
                ('user', models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('details_id', models.AutoField(auto_created=True, db_column='details_id', primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_pic', models.CharField(max_length=200)),
                ('goods_nprice', models.FloatField()),
                ('goods_num', models.IntegerField()),
                ('goods_xiaoji', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(db_column='goods_id', default='', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='myshop.ManagerMessage')),
                ('order', models.ForeignKey(db_column='order_id', default='', on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
        ),
    ]
