# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('userpass', models.CharField(default='', max_length=50)),
                ('nickname', models.CharField(default='', max_length=100, null=True)),
                ('shop_nickname', models.CharField(default='', max_length=100, null=True)),
                ('shop_logo', models.ImageField(default='', null=True, upload_to='uploads')),
                ('shop_address', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
