# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('userpass', models.IntegerField()),
            ],
        ),
    ]
