# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(default='', max_length=50)),
                ('goods_price', models.FloatField()),
                ('goods_xprice', models.FloatField()),
                ('goods_count', models.IntegerField(default='0')),
                ('goods_info', models.CharField(max_length=50)),
                ('goods_pic', models.ImageField(default='', upload_to='media/uploads')),
                ('goods_method', models.CharField(default='', max_length=50)),
                ('goods_address', models.CharField(default='', max_length=100)),
                ('goods_content', models.TextField()),
                ('manage', models.ForeignKey(db_column='manage_id', default='', on_delete=django.db.models.deletion.CASCADE, to='myshop.ManagerMessage')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('type_id', models.AutoField(auto_created=True, db_column='type_id', default=0, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('type_sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='type',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType'),
        ),
    ]
