# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('goods', '0001_initial'),
        ('myshop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('comment_id', models.AutoField(auto_created=True, db_column='comment_id', primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('huifu', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('details', models.ForeignKey(db_column='details_id', on_delete=django.db.models.deletion.CASCADE, to='cart.Order_details')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('manage', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='myshop.ManagerMessage')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
